services:
  - type: web
    name: alexamusicbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python __main__.py
    envVars:
      - key: API_ID
        value: "your_api_id"
      - key: API_HASH
        value: "your_api_hash"
      - key: BOT_TOKEN
        value: "your_bot_token"
    hooks:
      postDeploy:
        - apt-get update && apt-get install -y ffmpeg
